# 自定义的配置请在myprops下配置，不要自立门户(例如aa: bb)，
# 否则会有奇异的bug(实测发现单元测试可以跑，但tomcat启动后找不到配置的值)
myprops:
  whoami: uat # 环境
  confluence: # confluence相关
    username: admin
    password: admin@uat
    pureIp: conf-uat.wdjr.local
    urlHead: http://conf-uat.wdjr.local
  jenkins: # jenkins相关
    username: guoliang34
    password: 88888888
    pureIp: ci-uat.wdjr.local
    urlHead: http://ci-uat.wdjr.local
  jira: # jira相关
    username: admin
    password: admin@uat
    pureIp: jira-uat.wdjr.local
    urlHead: http://jira-uat.wdjr.local
  scm: # scm相关
    svn: 
      username: admin
      password: admin@123
      pureIp: svn-uat.wdjr.local
      urlHead: https://svn-uat.wdjr.local:4434
  ldap: # ldap相关
    enable: true
    userDnPatterns: cn={0}
    groupSearchBase: dc=wdjr
    managerDn: cn=yyyy,dc=wdjr
    managerPassword: yyyy@wdjr2018!@#
    url: ldap://10.215.4.108:389/
  switch: #功能开关
    enableSso: true  

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.215.4.111:3306/portal?useSSL=false
    username: portal
    password: Wanda@2017
  redis:
    database: 0
    host: localhost
    port: 6379
    password: Wanda@2017

logging:
  level:
    root: ERROR
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.hibernate: ERROR
    com.wanda.portal: INFO
  file: /var/log/portal.log
