# 自定义的配置请在myprops下配置，不要自立门户(例如aa: bb)，
# 否则会有奇异的bug(实测发现单元测试可以跑，但tomcat启动后找不到配置的值)
myprops:
  whoami: prod # 环境
  confluence: # confluence相关
    username: admin
    password: admin@123
    pureIp: conf.wdjr.local
    urlHead: http://conf.wdjr.local
  jenkins: # jenkins相关
    username: admin
    password: admin@123
    pureIp: ci.wdjr.local
    urlHead: http://ci.wdjr.local
  jira: # jira相关
    username: admin
    password: admin@123
    pureIp: jira.wdjr.local
    urlHead: http://jira.wdjr.local
  scm: # scm相关
    svn: 
      username: admin
      password: admin@123
      pureIp: svn.wdjr.local
      urlHead: http://svn.wdjr.local
  ldap: # ldap相关
    enable: true
    url: ldap://10.214.170.67:389/dc=wanda,dc=cn      
  switch: #功能开关
    enableSso: true  
                   
spring:
  datasource:
    password: Wanda@2017
    url: jdbc:mysql://192.168.0.17:3306/portal?useSSL=false
    username: portal
  redis:
    database: 0
    host: 192.168.0.17
    port: 6379
    password:

logging:
  level:
    root: ERROR
    org.springframework.web: DEBUG
    org.hibernate: ERROR
    com.wanda.portal: INFO
file: /var/log/portal.log
