#entitymanager:
#  packagesToScan: com.wanda.portal
myprops: 
  confluence: # confluence相关通用配置
    genericApi: /rest/api/
  jenkins: # jenkins相关通用配置
    jsonQueryJobsApi: "/api/json?tree=jobs[name,url,displayName]&pretty=true"
    createItem: /createItem
  jira: # jira相关通用配置
    genericApi: /rest/api/2/
    oldCreateApi: /rest/project-templates/1.0/createshared/   
  scm:
    svn:
      genericApi: /csvn/api/1/ 
         
server:
  port: '8083'
  
spring:
  profiles:
    active: uat

#    filters: stat
#    maxActive: 20
#    initialSize: 1
#    maxWait: 60000
#    minIdle: 1
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: select 'x'
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxOpenPreparedStatements: 20
  thymeleaf:
    cache: false  
    prefix: classpath:/templates/
    suffix: .html  
    encoding: UTF-8  
    servlet:
      content-type: text/html  
    mode: HTML5  
  redis:
    jedis:
      pool.max-active: 8
      pool.max-wait: -1
      pool.max-idle: 8
      pool.min-idle: 0
    timeout: 100000