# 自定义的配置请在myprops下配置，不要自立门户(例如aa: bb)，
# 否则会有奇异的bug(实测发现单元测试可以跑，但tomcat启动后找不到配置的值)
myprops:
  whoami: prod # 环境
  confluence: # confluence相关
    username: admin
    password: admin@123
    pureIp: 10.215.4.200
    urlHead: http://10.215.4.200:8090
  jenkins: # jenkins相关
    username: admin
    password: admin@123
    urlHead: http://10.215.4.154:8080
    pureIp: 10.215.4.154
  jira: # jira相关
    username: admin
    password: admin@123
    pureIp: 10.215.4.199
    urlHead: http://10.215.4.199:8080
  scm: # scm相关
    svn: 
      username: admin
      password: admin@123
      pureIp: 10.215.4.165
      urlHead: http://10.215.4.165:3343
  ldap: # ldap相关
    enable: true
    url: ldap://10.214.170.67:389/dc=wanda,dc=cn      
                  
spring:
  datasource:
    password: Wanda@2017
    url: jdbc:mysql://192.168.0.17:3306/portal?useSSL=false
    username: portal
  redis:
    database: 0
    host: 192.168.0.17
    port: 6379
    password: 